/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego_vibora;

/**
 *
 * @author Angel
 */
public class Configuraciones extends javax.swing.JPanel {
    /**
     * Creates new form Configuraciones
     */
    public Configuraciones() {
        initComponents();
    }
    
    public int getTablero_size() {
        switch (tablero_size_cbox.getSelectedItem().toString()) {
            case "Pequeño":
                return 20;
            case "Mediano":
                return 40;
            case "Grande":
                return 60;
            case "Muy grande":
                return 80;
            default:
                return 20;
        }
    }
    
    public boolean isBordes() {
        return tablero_bordes_box.isSelected();
    }
    
    public int getJugadores() {
        return Integer.parseInt(jugadores_cbox.getSelectedItem().toString());
    }
    
    public int getCuerpo() {
        return cuerpo_inicial_slider.getValue();
    }
    
    public int getVelocidad() {
        return velocidad_incial_slider.getValue();
    }
    
    public boolean isAumento_velocidad() {
        return aumento_velocidad_box.isSelected();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablero_size_panel = new javax.swing.JPanel();
        tablero_size_txt = new javax.swing.JLabel();
        tablero_size_cbox = new javax.swing.JComboBox<>();
        tablero_bordes_panel = new javax.swing.JPanel();
        tablero_bordes_txt = new javax.swing.JLabel();
        tablero_bordes_box = new javax.swing.JCheckBox();
        jugadores_panel = new javax.swing.JPanel();
        jugadores_txt = new javax.swing.JLabel();
        jugadores_cbox = new javax.swing.JComboBox<>();
        cuerpo_inicial_panel = new javax.swing.JPanel();
        cuerpo_inicial_txt = new javax.swing.JLabel();
        cuerpo_inicial_slider = new javax.swing.JSlider();
        velocidad_inicial_panel = new javax.swing.JPanel();
        velocidad_inicial_txt = new javax.swing.JLabel();
        velocidad_incial_slider = new javax.swing.JSlider();
        aumento_velocidad_panel = new javax.swing.JPanel();
        aumento_velocidad_txt = new javax.swing.JLabel();
        aumento_velocidad_box = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridLayout(6, 1));

        tablero_size_panel.setLayout(new java.awt.GridLayout(1, 0));

        tablero_size_txt.setText("Tamaño del tablero");
        tablero_size_panel.add(tablero_size_txt);

        tablero_size_cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pequeño", "Mediano", "Grande", "Muy grande" }));
        tablero_size_cbox.setSelectedIndex(1);
        tablero_size_panel.add(tablero_size_cbox);

        add(tablero_size_panel);

        tablero_bordes_panel.setLayout(new java.awt.GridLayout(1, 2));

        tablero_bordes_txt.setText("Bordes del tablero");
        tablero_bordes_panel.add(tablero_bordes_txt);
        tablero_bordes_panel.add(tablero_bordes_box);

        add(tablero_bordes_panel);

        jugadores_panel.setLayout(new java.awt.GridLayout(1, 2));

        jugadores_txt.setText("Jugadores");
        jugadores_panel.add(jugadores_txt);

        jugadores_cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jugadores_panel.add(jugadores_cbox);

        add(jugadores_panel);

        cuerpo_inicial_panel.setLayout(new java.awt.GridLayout(1, 2));

        cuerpo_inicial_txt.setText("Cuerpo inicial");
        cuerpo_inicial_panel.add(cuerpo_inicial_txt);

        cuerpo_inicial_slider.setMajorTickSpacing(1);
        cuerpo_inicial_slider.setMaximum(10);
        cuerpo_inicial_slider.setMinimum(3);
        cuerpo_inicial_slider.setMinorTickSpacing(1);
        cuerpo_inicial_panel.add(cuerpo_inicial_slider);

        add(cuerpo_inicial_panel);

        velocidad_inicial_panel.setLayout(new java.awt.GridLayout(1, 2));

        velocidad_inicial_txt.setText("Velocidad inicial");
        velocidad_inicial_panel.add(velocidad_inicial_txt);

        velocidad_incial_slider.setMajorTickSpacing(1);
        velocidad_incial_slider.setMaximum(10);
        velocidad_incial_slider.setMinimum(1);
        velocidad_incial_slider.setMinorTickSpacing(1);
        velocidad_incial_slider.setValue(5);
        velocidad_inicial_panel.add(velocidad_incial_slider);

        add(velocidad_inicial_panel);

        aumento_velocidad_panel.setLayout(new java.awt.GridLayout(1, 2));

        aumento_velocidad_txt.setText("Aumento de velocidad");
        aumento_velocidad_panel.add(aumento_velocidad_txt);

        aumento_velocidad_box.setSelected(true);
        aumento_velocidad_panel.add(aumento_velocidad_box);

        add(aumento_velocidad_panel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aumento_velocidad_box;
    private javax.swing.JPanel aumento_velocidad_panel;
    private javax.swing.JLabel aumento_velocidad_txt;
    private javax.swing.JPanel cuerpo_inicial_panel;
    private javax.swing.JSlider cuerpo_inicial_slider;
    private javax.swing.JLabel cuerpo_inicial_txt;
    private javax.swing.JComboBox<String> jugadores_cbox;
    private javax.swing.JPanel jugadores_panel;
    private javax.swing.JLabel jugadores_txt;
    private javax.swing.JCheckBox tablero_bordes_box;
    private javax.swing.JPanel tablero_bordes_panel;
    private javax.swing.JLabel tablero_bordes_txt;
    private javax.swing.JComboBox<String> tablero_size_cbox;
    private javax.swing.JPanel tablero_size_panel;
    private javax.swing.JLabel tablero_size_txt;
    private javax.swing.JSlider velocidad_incial_slider;
    private javax.swing.JPanel velocidad_inicial_panel;
    private javax.swing.JLabel velocidad_inicial_txt;
    // End of variables declaration//GEN-END:variables
}
